<link rel="stylesheet" type="text/css" href="/css/admin/login.css" />

<form class="form-signin" method="post" action="">
	<h2 class="form-signin-heading">Log in</h2>
	
	<?php if (isset($this->error)): ?>
		<div class="alert">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<?php echo $this->error; ?>
		</div>
	<?php endif; ?>
	
	<input type="text" name="email" class="input-block-level" placeholder="E-mail adres" value="<?php if (isset($this->postVars['email'])) echo $this->postVars['email']; ?>" /><br />
	<input type="password" name="password" class="input-block-level" placeholder="Wachtwoord" /><br />
	
	<input type="submit" class="btn btn-primary" type="submit" />
</form>