<div id="footer">

	<div class="divider"></div>
	
	<div class="left">
	
		<h4>Website</h4>
		<p>Ruben Coolen<br />
		Monsveld 14<br />
		3990 Peer<br />
		<a href="mailto:rubencoolen@live.be">rubencoolen@live.be</a></p>
	
	</div>
	<div class="right">
	
		<h4>Contact</h4>
		<p>Floris Thijs<br />
		Stuifzandstraat 16<br />
		3900 Overpelt<br />
		<a href="mailto:contact@floristhijs.be">contact@floristhijs.be</a></p>
	
	</div>
	<div class="clear"></div>

</div>