<!doctype html>
<html>

<head>

	<title><?php echo $this->title ?></title>
	
	<link rel="shortcut icon" type="image/x-icon" href="/graphics/layout/favicon.ico" />
	
	<link rel="stylesheet" href="/css/style.css" />
	
	<link rel="stylesheet" href="/css/nivo-slider.css" />

	<?php echo $this->styles ?>
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	
	<script src="/scripts/jquery.nivo.slider.js"></script>
	
	<script src="/scripts/modernizr.js"></script>
	
	<script src="http://cssrefresh.frebsite.nl/js/cssrefresh.js"></script>
	
	<?php echo $this->scripts ?>
	
	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function() {
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	ga('create', 'UA-40836429-1', 'floristhijs.be');
	ga('send', 'pageview');
	</script>

</head>

<body>

<div id="social">

	<div id="email" title="Go to my contact page"><a href="<?php echo $this->createUrl('front', 'index', 'contact') ?>"><img src="/graphics/layout/toplogos/email.png" /></a></div>
	<div id="vimeo" title="Check out my videos on Vimeo"><a href="#"><img src="/graphics/layout/toplogos/vimeo.png" /></a></div>
	<div id="facebook" title="Stalk me on Facebook"><a href="https://www.facebook.com/floris.thijs" target="_blank"><img src="/graphics/layout/toplogos/facebook.png" /></a></div>
	<div id="linkedin" title="Visit my LinkedIn"><a href="#"><img src="/graphics/layout/toplogos/linkedin.png" /></a></div>
	<div class="clear"></div>

</div>

<div id="page_container">

	<div id="page_header">
	
		<div id="page_header_body">
		
			<a href="/"><img id="page_header_body_title" src="/graphics/layout/header_title.png" /></a>
			<img id="page_header_body_right" src="/graphics/layout/header_right.png" />
		
		</div>
	
	</div>
	<div id="page_middle">
	
		
	
	</div>
	<div id="content_container">
		<?php $this->__render('layout/front/menu') ?>
		<div id="content_body">

			<?php $this->__render('content') ?>
			
			<?php $this->__render('layout/front/footer') ?>
		
		</div>
	
	</div>

</div>

</body>

</html>