<div class="navbar navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			
			<a class="brand" href="<?php echo $this->createUrl('admin'); ?>" title="Home"><?php echo $this->config['system']['name']; ?></a>
			<div class="nav-collapse collapse">
				<ul class="nav" role="navigation">
					<li><a href="<?php echo $this->createUrl('front'); ?>" title="Naar de front" target="_blank">Naar de front</a></li>
				</ul>
				<ul class="nav pull-right">
					<li>
						
					</li>
					<?php if ($this->getUser('admin')): ?>
						<?php $user = $this->getUser('admin'); ?>
						<li class="dropdown">
							<a href="#" id="nav-top-dropdown" role="button" class="dropdown-toggle" data-toggle="dropdown">Ingelogd als <strong><?php echo $user->getFullname(); ?></strong> <b class="caret"></b></a>
							<ul class="dropdown-menu" role="menu" aria-labelledby="nav-top-dropdown">
								<li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->createUrl('admin', 'user', 'profile'); ?>">Profiel</a></li>
		                        <li role="presentation" class="divider"></li>
		                        <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->createUrl('admin', 'user', 'logout'); ?>">Uitloggen</a></li>
							</ul>
						</li>
					<?php else: ?>
						<li>
							<a href="<?php echo $this->createUrl('admin', 'user', 'login'); ?>">Log in</a>
						</li>
					<?php endif; ?>
				</ul>
			</div>
		</div>
	</div>
</div>

<script>
$('.dropdown-toggle').dropdown();
</script>