<a class="thumbnail" href="/graphics/portfolio/full/image-001.jpg" rel="shadowbox[gallery]" title="Brug 1">

	<img src="/graphics/portfolio/image-001.jpg" class="image transition" />
	
	<div class="title transition">Brug 1</div>
	<div class="description transition">Brug 1 uitleg</div>
	
	<div class="overlay"></div>

</a>

<a class="thumbnail" href="/graphics/portfolio/full/image-002.jpg" rel="shadowbox[gallery]" title="Bos 1">

	<img src="/graphics/portfolio/image-002.jpg" class="image transition" />
	
	<div class="title transition">Bos 1</div>
	<div class="description transition">Bos 1 uitleg</div>
	
	<div class="overlay"></div>

</a>

<a class="thumbnail" href="/graphics/portfolio/full/image-003.jpg" rel="shadowbox[gallery]" title="Berg 1">

	<img src="/graphics/portfolio/image-003.jpg" class="image transition" />
	
	<div class="title transition">Berg 1</div>
	<div class="description transition">Berg 1 uitleg</div>
	
	<div class="overlay"></div>

</a>

<a class="thumbnail" href="/graphics/portfolio/full/image-001.jpg" rel="shadowbox[gallery]" title="Brug 2">

	<img src="/graphics/portfolio/image-001.jpg" class="image transition" />
	
	<div class="title transition">Brug 2</div>
	<div class="description transition">Brug 2 uitleg</div>
	
	<div class="overlay"></div>

</a>

<a class="thumbnail" href="http://vimeo.com/moogaloop.swf?clip_id=25186640&autoplay=1" rel="shadowbox[gallery];width=600;height=380" title="Resonance">

	<img src="/graphics/portfolio/resonance.png" class="image transition" />
	
	<div class="title transition">Resonance</div>
	<div class="description transition">Exploring the relationship between geometry and audio in unique ways</div>
	
	<div class="overlay video"></div>

</a>

<script>
Shadowbox.init({
    handleOversize: "resize",
    autoplayMovies: true,
    continuous: true
});
</script>